apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwfgtr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwfgtr
  template:
    metadata:
      labels:
        app: qwfgtr
    spec:
      containers:
      - image: okteto.dev/qwfgtr:latest
        name: qwfgtr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/LandingStartups-html.zip"
        - name: Vless_UUID
          value: "fb49ad70-2a5a-46b2-a12d-3a2292de9d18"
        - name: Vless_Path
          value: "/fb49ad70-2a5a-46b2-a12d-3a2292de9d18-vless"
        - name: Vmess_UUID
          value: "fb49ad70-2a5a-46b2-a12d-3a2292de9d18"
        - name: Vmess_Path
          value: "/fb49ad70-2a5a-46b2-a12d-3a2292de9d18-vmess"
        - name: Share_Path
          value: "/vpqqk"
